# Generated by Django 4.2.16 on 2024-11-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_telefon_raqam'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefon',
            field=models.CharField(default='Kiritilmagan', max_length=15),
        ),
    ]
