# Generated by Django 4.2.16 on 2024-11-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maktab',
            field=models.CharField(default='Kiritilmagan', max_length=300),
        ),
    ]
