# Generated by Django 3.2.25 on 2024-11-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefon',
            field=models.CharField(default='Kiritilmagan', max_length=20),
        ),
    ]
