# Generated by Django 4.2.16 on 2024-10-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ['-time']},
        ),
    ]
