# Generated by Django 3.2.25 on 2024-11-14 10:16

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kontest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('image', models.ImageField(upload_to='kontest/')),
                ('top', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Masala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('kirish', ckeditor.fields.RichTextField()),
                ('chiqish', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('hotira', models.IntegerField(default=150)),
                ('muallif', models.CharField(max_length=150)),
                ('qiyinchilik', models.CharField(choices=[('Oson', 'Oson'), ("O'rta", "O'rta"), ('Qiyin', 'Qiyin'), ('Murakkab', 'Murakkab')], max_length=150)),
                ('timeout', models.DurationField(default=datetime.timedelta(seconds=10))),
                ('ball', models.IntegerField(default=5)),
                ('kontest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masalalar', to='kontest.kontest')),
            ],
            options={
                'verbose_name': 'Masalalar',
                'verbose_name_plural': 'Masalalar',
            },
        ),
        migrations.CreateModel(
            name='UserMasalaRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('C++', 'C++'), ('C', 'C'), ('Java', 'Java'), ('Python', 'Python')], max_length=150)),
                ('script', models.FileField(upload_to=kontest.models.PathAndRename('scripts/'))),
                ('script_result', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(default='Waiting...', max_length=150)),
                ('masala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishlaganlar', to='kontest.masala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishlangan_masalalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='UserKontestRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='kontest.kontest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kirish', models.TextField(max_length=150)),
                ('output', models.CharField(max_length=150)),
                ('masala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='kontest.masala')),
            ],
        ),
    ]
