# Generated by Django 3.2.25 on 2024-11-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontest', '0002_masala_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
