# Generated by Django 5.1.3 on 2024-11-18 08:15

import kontest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontest', '0003_test_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermasalarelation',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermasalarelation',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to=kontest.models.PathAndRename('scripts/')),
        ),
    ]
