# Generated by Django 5.1.3 on 2024-11-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontest', '0004_usermasalarelation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkontestrelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermasalarelation',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('C', 'C'), ('Java', 'Java'), ('Python', 'Python'), ('Go', 'Go')], max_length=150),
        ),
    ]
