# Generated by Django 5.1.3 on 2024-11-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontest', '0006_alter_test_kirish_alter_test_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkontestrelation',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
